context:
  version: "0.21.1"

package:
  name: openai-agents
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/o/openai-agents/openai_agents-${{ version }}.tar.gz
    sha256: 7d6519bed92542b2a7160cd50edca0721c64d5f06616d85c6de477f237b8423c

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - openai >=2.26.0,<3
    - pydantic >=2.12.2,<3
    - griffelib >=2,<3
    - typing-extensions >=4.12.2,<5
    - requests >=2.0,<3
    - types-requests >=2.0,<3
    - websockets >=15.0,<16
    - mcp >=1.19.0,<2

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - agents
      pip_check: true

about:
  summary: A lightweight, powerful framework for multi-agent workflows
  homepage: https://github.com/openai/openai-agents-python
  license: MIT
  license_file: LICENSE
extra:
  recipe-maintainers:
    - timkpaine
    - moritzwilksch
